# Gemma 4 adaptation — new in this fork (github.com/anthropics/jacobian-lens is upstream).
# SPDX-License-Identifier: Apache-2.0
"""Structure and full MOCK execution of the L32 follow-up notebook.

The execution tests run every code cell in one namespace in a clean
interpreter, with the committed switches left alone. That checks two things at
once: the notebook works end to end on CPU, and opening it starts nothing.

A second run flips the paired-reference switches, which is the only
configuration that is meant to change a conclusion (it licenses the cross-layer
comparison).

The notebook is generated by ``scripts/_build_l32_followup_notebook.py``; the
structural tests here are what keep the generated file honest.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
NOTEBOOK_PATH = (
    REPO_ROOT / "notebooks" / "multimodal_jspace_spokencoco_l32_followup_colab.ipynb"
)
BUILDER = REPO_ROOT / "scripts" / "_build_l32_followup_notebook.py"
RUNNER = Path(__file__).resolve().parent / "_l32_followup_notebook_runner.py"

#: Every switch the brief names. All must be committed as ``False``.
SWITCHES = (
    "RUN_REAL_L32_FOLLOWUP",
    "RUN_MODEL_STAGES",
    "CONFIRM_MODEL_LOAD",
    "CONFIRM_CAUSAL_BUDGET",
    "RUN_PAIRED_L35_REFERENCE",
    "CONFIRM_PAIRED_REFERENCE_BUDGET",
)

REQUIRED_SECTIONS = [
    "bootstrap repository",
    "switches, pins and the design",
    "mount drive",
    "runtime and versions",
    "resolve the published l32 lens",
    "comparability with the completed l35 study",
    "the open prompt",
    "the frozen spokencoco selection design",
    "capability admissibility",
    "exact pass budgets",
    "load the model",
    "run fingerprint",
    "j-space codes and the representational diagnostics",
    "the causal test at layer 32",
    "native output-convergence audit at layer 32",
    "the paired l35 reference",
    "the five verdicts",
    "the conditional next step",
]


@pytest.fixture(scope="module")
def notebook():
    return json.loads(NOTEBOOK_PATH.read_text(encoding="utf-8"))


def _code_cells(payload):
    return [cell for cell in payload["cells"] if cell["cell_type"] == "code"]


def _source(payload):
    return "\n".join("".join(cell["source"]) for cell in payload["cells"])


def _code_source(payload):
    return "\n".join("".join(cell["source"]) for cell in _code_cells(payload))


# ---------------------------------------------------------------- structure


def test_notebook_is_valid_and_output_free(notebook):
    assert notebook["nbformat"] == 4
    for index, cell in enumerate(_code_cells(notebook)):
        assert cell["outputs"] == [], f"code cell {index} has stored outputs"
        assert cell["execution_count"] is None, f"code cell {index} has an exec count"


def test_the_committed_notebook_matches_its_builder():
    result = subprocess.run(
        [sys.executable, str(BUILDER)], capture_output=True, text=True, cwd=REPO_ROOT
    )
    assert result.returncode == 0, result.stderr
    assert (
        subprocess.run(
            ["git", "diff", "--quiet", "--", str(NOTEBOOK_PATH)], cwd=REPO_ROOT
        ).returncode
        == 0
    ), (
        "the committed notebook differs from what the builder produces; "
        "edit scripts/_build_l32_followup_notebook.py and re-run it"
    )


def test_every_code_cell_parses(notebook):
    import ast

    for cell in _code_cells(notebook):
        ast.parse("".join(cell["source"]))


@pytest.mark.parametrize("section", REQUIRED_SECTIONS)
def test_required_sections_are_present(notebook, section):
    assert section in _source(notebook).lower()


@pytest.mark.parametrize("switch", SWITCHES)
def test_every_switch_is_committed_false(notebook, switch):
    assert f"{switch} = False" in _code_source(notebook)
    assert f"{switch} = True" not in _code_source(notebook)


def test_the_notebook_never_hardcodes_the_published_artifact_filename(notebook):
    source = _code_source(notebook)
    assert "lens.early.layer32" not in source, (
        "the L32 artifact filename is resolved from the extension run's own "
        "metadata; typing it here would make discovery decorative"
    )
    assert "discover_published_l32_lens" in source


def test_the_reference_lens_is_pinned_at_its_own_scale(notebook):
    source = _code_source(notebook)
    # The L35 reference IS named, because it is the completed calibration's
    # published artifact and this study does not rediscover it.
    assert "lens.layer35.scale100.validated.pt" in source
    assert "REFERENCE_LENS_FITTED_SCALE = 100" in source
    assert "LENS_FITTED_SCALE = 250" in source


def test_steering_is_never_renamed_as_a_coordinate_swap(notebook):
    source = _source(notebook).lower()
    assert "not the anthropic two-coordinate swap" in source
    assert "source-derived j-space causal steering" in source
    # The distinction is stated, and the swap module is not imported.
    assert "from jlens.mmpilot.coordinate_swap import" not in _code_source(notebook)


def test_the_report_phrasing_rule_is_enforced_in_the_notebook(notebook):
    source = _code_source(notebook)
    assert "assert_report_phrasing" in source
    text = _source(notebook).lower()
    assert "before native direct-readout convergence" in text
    # Every occurrence of a forbidden phrase must sit inside a passage that is
    # ruling it out, not asserting it. Checked over a window rather than a line,
    # because the prose wraps.
    for phrase in ("pre-linguistic", "language-free", "before language exists"):
        start = 0
        while (index := text.find(phrase, start)) != -1:
            window = text[max(0, index - 400) : index + 400]
            assert "never" in window, f"{phrase!r} used as a claim near: {window}"
            start = index + len(phrase)


def test_no_adjacent_layer_is_fitted_or_tested(notebook):
    source = _code_source(notebook)
    for forbidden in ("33", "34"):
        assert f"CAUSAL_LAYER = {forbidden}" not in source
    assert "adjacent_layer_recommendation" in source
    assert "not** fitted or tested here" in _source(notebook)


def test_completed_runs_are_named_as_protected(notebook):
    source = _code_source(notebook)
    for prefix in ("rgext_", "mmaudio_", "rgcalib_"):
        assert f'"{prefix}"' in source
    assert "PROTECTED_RUN_PREFIXES" in source


# ------------------------------------------------------------ MOCK execution


def _run(tmp_path, *overrides):
    environment = dict(os.environ)
    environment.pop("PYTHONPATH", None)
    environment["MMPILOT_REPO_DIR"] = str(REPO_ROOT)
    environment["MMPILOT_SCRATCH"] = str(tmp_path / "scratch")
    result = subprocess.run(
        [sys.executable, str(RUNNER), str(NOTEBOOK_PATH), *overrides],
        capture_output=True,
        text=True,
        cwd=str(tmp_path),
        env=environment,
    )
    payload = json.loads(result.stdout.strip().splitlines()[-1])
    assert payload.get("ok"), payload
    return payload


@pytest.fixture(scope="module")
def mock_run(tmp_path_factory):
    return _run(tmp_path_factory.mktemp("l32nb"))


@pytest.fixture(scope="module")
def mock_run_with_reference(tmp_path_factory):
    return _run(
        tmp_path_factory.mktemp("l32nbref"),
        "RUN_PAIRED_L35_REFERENCE=True",
        "CONFIRM_PAIRED_REFERENCE_BUDGET=True",
    )


def test_the_mock_notebook_runs_end_to_end(mock_run):
    assert mock_run["n_cells"] > 20
    assert mock_run["mock_proves_pipeline_only"] is True
    assert mock_run["report_schema"] == "jlens.mmpilot.l32_followup_report.v1"


def test_the_mock_run_is_deterministic(tmp_path_factory, mock_run):
    again = _run(tmp_path_factory.mktemp("l32nb2"))
    for key in (
        "VERDICT_A",
        "VERDICT_B",
        "VERDICT_C",
        "VERDICT_D",
        "VERDICT_E",
        "SELECTED_NAMES",
        "FOCAL_CONCEPTS",
        "OPEN_QUESTION",
        "DISCOVERY_REFUSALS",
        "RECOMMENDATION.recommendation",
    ):
        assert again[key] == mock_run[key], f"{key} differed between MOCK runs"


def test_the_mock_run_exercises_every_discovery_refusal(mock_run):
    from jlens.mmpilot.mock import MOCK_EXTENSION_DEFECTS

    refusals = mock_run["DISCOVERY_REFUSALS"]
    for defect in MOCK_EXTENSION_DEFECTS:
        assert refusals[defect] == "ArtifactDiscoveryRefused"
    for report_defect in ("mock_mode_report", "no_go_verdict", "nothing_published"):
        assert refusals[report_defect] == "ArtifactDiscoveryRefused"


def test_the_prompt_never_lists_the_candidates(mock_run):
    question = mock_run["OPEN_QUESTION"]
    for concept in mock_run["SELECTED_NAMES"]:
        assert concept not in question.lower(), (
            f"the candidate {concept!r} appears in the model-visible question"
        )
    assert "which one of these is present" not in question.lower()


def test_the_intervention_family_is_recorded_as_steering(mock_run):
    assert mock_run["intervention_family"] == "source_derived_jspace_steering"


def test_the_cross_layer_comparison_is_refused_without_the_reference(mock_run):
    assert mock_run["COMPARABILITY.paired_reference_required"] is True
    assert mock_run["CROSS_LAYER_ALLOWED_WITHOUT_REFERENCE"] is False
    assert mock_run["CROSS_LAYER.licensed"] is False
    # Every L32 verdict is still produced.
    assert mock_run["VERDICT_A"] == "PASSED"
    assert mock_run["VERDICT_C"] is not None
    assert mock_run["VERDICT_E"] is not None


def test_the_paired_reference_licenses_the_comparison(mock_run_with_reference):
    assert mock_run_with_reference["PAIRED_REFERENCE_ENABLED"] is True
    assert mock_run_with_reference["CROSS_LAYER.licensed"] is True


def test_the_phrasing_check_passes_on_the_generated_report(mock_run):
    assert mock_run["PHRASING.passed"] is True


def test_the_recommendation_follows_the_predeclared_rule(mock_run):
    # The MOCK model's lm_head rows ARE the concept vectors and its final norm
    # is the identity, so its native readout is analytically clean and layer 32
    # reads as CONVERGED. That is the correct MOCK outcome, and it is the branch
    # that must send the search to EARLIER layers, not to 33/34.
    assert mock_run["VERDICT_D"] == "CONVERGED"
    assert mock_run["VERDICT_E"] == "TRANSFER_AT_OR_AFTER_CONVERGENCE"
    assert mock_run["RECOMMENDATION.recommendation"] == (
        "investigate_layers_earlier_than_32"
    )


# ------------------------------------- what the run wrote, and what it did not


def _report(payload):
    return json.loads(
        (Path(payload["run_dir"]) / "l32_followup_report.json").read_text(
            encoding="utf-8"
        )
    )


def test_the_run_left_no_torn_units(mock_run):
    resume = _report(mock_run)["resume"]
    assert resume["invalid_units"] == []
    assert resume["status"] in ("starting", "resuming")


def test_train_and_heldout_images_are_disjoint(mock_run):
    provenance = _report(mock_run)["split_provenance"]
    assert provenance["train_heldout_image_overlap"] == []
    assert provenance["leakage"]["ok"] is True


def test_one_recording_per_photograph(mock_run):
    provenance = _report(mock_run)["split_provenance"]
    assert provenance["n_distinct_recordings"] == provenance["n_groups"]
    assert provenance["n_distinct_images"] == provenance["n_groups"]


def test_retrieval_excludes_the_same_image_not_only_the_same_group(mock_run):
    """The exclusion is by image identity, and it is reported per direction.

    Under the ``image_unique`` profile the subset keeps exactly one synchronized
    group per photograph, so ``n_excluded_same_image_different_group`` is
    necessarily 0 — there is no sibling group left to exclude. That is the
    *stronger* state, not a missing check: the sibling route was closed at
    selection rather than at retrieval. What must hold either way is that the
    image-superseding rule is the one in force, that every query's own group was
    excluded, and that the sibling counter is reported so a future subset that
    does keep siblings is visibly covered.
    """
    from jlens.mmpilot.jspace import EXCLUSION_RULE_VERSION

    assert EXCLUSION_RULE_VERSION == "exclude_same_image_id_supersedes_group.v1"
    report = _report(mock_run)
    provenance = report["split_provenance"]
    assert provenance["n_distinct_images"] == provenance["n_groups"]

    representational = report["representational"]
    layer = next(iter(representational))
    pairs = representational[layer]["pairs"]
    assert len(pairs) == 6, f"expected six directed pairs, got {sorted(pairs)}"
    for name, entry in pairs.items():
        exclusions = entry["exclusions"]
        assert exclusions["rule_version"] == EXCLUSION_RULE_VERSION, name
        assert "n_excluded_same_image_different_group" in exclusions, name
        assert exclusions["n_excluded_same_group"] == exclusions["n_sources"], name
        assert exclusions["n_sources_without_eligible_target"] == 0, name


def test_the_causal_summary_is_aggregated_by_photograph(mock_run):
    report = _report(mock_run)
    verdict = report["verdicts"]["C_causal_transfer"]
    assert verdict is not None
    for cell in verdict["cells"]:
        if cell.get("evaluated"):
            assert "n_distinct_images" in cell
            assert "n_positive_images" in cell


def test_capability_admissibility_is_applied_and_disclosed(mock_run):
    verdict = _report(mock_run)["verdicts"]["C_causal_transfer"]
    admissibility = verdict["capability_admissibility"]
    assert set(admissibility["fixed_concepts"]) == set(mock_run["FOCAL_CONCEPTS"])
    assert "no_post_hoc_replacement" in admissibility
    for cell in verdict["cells"]:
        assert "counted_toward_verdict" in cell
        assert "capability_admissible" in cell


def test_the_native_head_agreement_is_recorded_as_not_run_in_mock(mock_run):
    agreement = _report(mock_run)["native_head_agreement"]
    assert agreement["comparison_ran"] is False
    assert agreement["required"] is False


def test_the_convergence_criterion_thresholds_were_not_touched(mock_run):
    from jlens.mmpilot.convergence import CONVERGENCE_CRITERION

    convergence = _report(mock_run)["convergence"]
    assert convergence["criterion_thresholds_unchanged"] is True
    assert convergence["criterion_digest"] == CONVERGENCE_CRITERION.digest
    assert convergence["cross_layer_rule_used"] is False


def test_the_convergence_controls_all_ran(mock_run):
    from jlens.mmpilot.convergence import CONTROL_VARIANTS

    controls = _report(mock_run)["convergence"]["controls"]
    per_layer = controls["per_layer"]
    cell = per_layer[next(iter(per_layer))]
    for variant in CONTROL_VARIANTS:
        entry = cell["controls"][variant]
        # Each control is scored on the metric it actually perturbs — the label
        # shuffle on target accuracy, the other two on agreement with the
        # model's own answer — so the compared field is named, not assumed.
        assert entry["compared_field"] in (
            "target_accuracy_argmax",
            "clean_agreement_argmax",
        ), (variant, entry["compared_field"])
        assert "control_value" in entry
        assert "chance_rate" in entry
    assert "wrong_layer_control_note" in controls
    assert "all_controls_passed" in controls


def test_the_fingerprint_records_every_named_field(mock_run):
    from jlens.mmpilot.l32_followup import FINGERPRINT_FIELDS

    fingerprint = _report(mock_run)["followup_fingerprint"]
    for name in FINGERPRINT_FIELDS:
        assert name in fingerprint, f"{name} missing from the run fingerprint"
    assert fingerprint["fingerprint_digest"].startswith("sha256:")


def test_an_incompatible_resume_is_refused(mock_run, tmp_path):
    """A directory written under one configuration refuses another."""
    from jlens.mmpilot.store import IncompatibleStateError, RunFingerprint, UnitStore

    run_dir = Path(mock_run["run_dir"])
    stored = json.loads((run_dir / "fingerprint.json").read_text(encoding="utf-8"))
    stored.pop("written_utc", None)
    changed = dict(stored)
    changed["selection_config"] = {
        **stored["selection_config"],
        "capability_protocol": "gemma-it-chat-balanced-options-v1",
    }
    with pytest.raises(IncompatibleStateError, match="different configuration"):
        UnitStore(run_dir, RunFingerprint(**changed)).open()


def test_the_open_protocol_is_bound_into_the_stored_fingerprint(mock_run):
    run_dir = Path(mock_run["run_dir"])
    stored = json.loads((run_dir / "fingerprint.json").read_text(encoding="utf-8"))
    selection = stored["selection_config"]
    assert selection["capability_protocol"] == "mmpilot.open_entity_identification.v1"
    assert selection["candidate_ordering_protocol"] == (
        "external_scorer_only_no_prompt_order.v1"
    )
    assert stored["intervention_config"]["intervention_family"] == (
        "source_derived_jspace_steering"
    )


def test_the_run_wrote_only_into_its_own_directory(mock_run, tmp_path_factory):
    run_dir = Path(mock_run["run_dir"])
    extension_run = run_dir.parent.parent / "extension_run"
    assert run_dir.is_dir()
    if extension_run.is_dir():
        written = [
            path
            for path in extension_run.rglob("*")
            if path.is_file() and path.suffix not in (".pt", ".json")
        ]
        assert written == [], f"the extension run was written into: {written}"
