# Gemma 4 adaptation — new in this fork (github.com/anthropics/jacobian-lens is upstream).
# SPDX-License-Identifier: Apache-2.0
"""Structure and full MOCK execution of the L32 convergence-resolution notebook.

The execution tests run every code cell in one namespace in a clean interpreter,
with the committed switches left alone. That checks two things at once: the
notebook works end to end on CPU, and opening it starts nothing.

Three further runs flip exactly one thing each — the Stage-B override, an
interrupted session, and a resumed one — because those are the paths whose
failure modes are silent.

The notebook is generated by ``scripts/_build_l32_resolution_notebook.py``; the
structural tests here are what keep the generated file honest.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
NOTEBOOK_PATH = (
    REPO_ROOT
    / "notebooks"
    / "multimodal_jspace_l32_convergence_resolution_colab.ipynb"
)
BUILDER = REPO_ROOT / "scripts" / "_build_l32_resolution_notebook.py"
RUNNER = Path(__file__).resolve().parent / "_l32_resolution_notebook_runner.py"

#: Every switch the brief names. All must be committed as ``False``.
SWITCHES = (
    "RUN_REAL_L32_CONVERGENCE_RESOLUTION",
    "PREPROCESSING_ONLY",
    "RUN_MODEL_STAGE",
    "CONFIRM_MODEL_LOAD",
    "CONFIRM_STAGE_A_BUDGET",
    "RUN_STAGE_B_CAUSAL_REPLICATION",
    "CONFIRM_STAGE_B_BUDGET",
    "ALLOW_MANIFEST_REBUILD",
)

REQUIRED_SECTIONS = [
    "bootstrap repository",
    "switches, pins and the frozen design",
    "mount drive",
    "runtime report",
    "resolve, verify and load the published l32 lens",
    "the predeclared sample size",
    "cached data loading",
    "the fresh population",
    "the open prompt",
    "pass budgets and the confirmation gates",
    "the retrying media loaders",
    "the run fingerprint, then stage a",
    "the native direct readout at layer 32",
    "the one primary verdict",
    "the conditional causal replication",
    "synthesis with the completed causal evidence",
    "write the artifacts",
    "resume state",
]


@pytest.fixture(scope="module")
def notebook():
    return json.loads(NOTEBOOK_PATH.read_text(encoding="utf-8"))


def _code_cells(payload):
    return [cell for cell in payload["cells"] if cell["cell_type"] == "code"]


def _source(payload):
    return "\n".join("".join(cell["source"]) for cell in payload["cells"])


def _code_source(payload):
    return "\n".join("".join(cell["source"]) for cell in _code_cells(payload))


# ---------------------------------------------------------------- structure


def test_notebook_is_valid_and_output_free(notebook):
    assert notebook["nbformat"] == 4
    for index, cell in enumerate(_code_cells(notebook)):
        assert cell["outputs"] == [], f"code cell {index} has stored outputs"
        assert cell["execution_count"] is None, f"code cell {index} has an exec count"


def test_the_committed_notebook_matches_its_builder():
    result = subprocess.run(
        [sys.executable, str(BUILDER)], capture_output=True, text=True, cwd=REPO_ROOT
    )
    assert result.returncode == 0, result.stderr
    assert (
        subprocess.run(
            ["git", "diff", "--quiet", "--", str(NOTEBOOK_PATH)], cwd=REPO_ROOT
        ).returncode
        == 0
    ), (
        "the committed notebook differs from what the builder produces; "
        "edit scripts/_build_l32_resolution_notebook.py and re-run it"
    )


def test_every_code_cell_parses(notebook):
    import ast

    for cell in _code_cells(notebook):
        ast.parse("".join(cell["source"]))


@pytest.mark.parametrize("section", REQUIRED_SECTIONS)
def test_required_sections_are_present(notebook, section):
    assert section in _source(notebook).lower()


@pytest.mark.parametrize("switch", SWITCHES)
def test_every_switch_is_committed_false(notebook, switch):
    """Assignments only — the switch names also appear in advice the cells print.

    Anchored at the start of a line, which is exactly what the notebook runner
    rewrites when a test flips a switch, so the two agree about what an
    assignment is.
    """
    assignments = [
        line.strip()
        for line in _code_source(notebook).splitlines()
        if line.startswith(f"{switch} = ")
    ]
    assert assignments == [f"{switch} = False"], assignments


def test_the_notebook_never_hardcodes_the_published_artifact_filename(notebook):
    source = _code_source(notebook)
    assert "lens.early.layer32" not in source
    assert "discover_published_l32_lens" in source


def test_audio_protocol_validator_is_imported_from_its_defining_module(notebook):
    """Guard the real-model path, which the CPU MOCK run cannot import-test."""
    source = _code_source(notebook)
    assert "from jlens.mmpilot.tri_modal import assert_audio_protocol" in source
    assert "from jlens.mmpilot.audio import assert_audio_protocol" not in source


def test_real_model_cell_uses_existing_package_entry_points(notebook):
    """The real-only branch must use the APIs exercised by existing studies."""
    source = _code_source(notebook)
    assert "from jlens.mmpilot.preflight import check_call_contracts" in source
    assert "from jlens.mmpilot.real_backend import build_real_backend" in source
    assert "from jlens.mmpilot.preflight import preflight" not in source
    assert "load_real_bundle" not in source
    assert "MODEL = BUNDLE.lens_model" in source
    assert "resolve_audio=True" in source


def test_the_cache_is_loaded_never_rebuilt_on_the_default_path(notebook):
    source = _code_source(notebook)
    assert "load_expanded_manifest" in source
    assert "ALLOW_MANIFEST_REBUILD = False" in source
    assert 'f"{COMPLETED_RUN_DIRS[0]}/expanded_manifest.json"' in source
    # The only build_expanded_manifest call sits inside the MOCK-only cache
    # manufacturing branch, which the real path never enters.
    assert source.count("expansion_module.build_expanded_manifest(") == 1
    assert "if not RUN_REAL_L32_CONVERGENCE_RESOLUTION and not Path(" in source


def test_the_guessed_dataset_level_manifest_path_is_gone(notebook):
    """The derived namespace is where PREPROCESSING writes, never the manifest.

    The bug this guards was a manifest path guessed at
    ``.../cstf_spokencoco_derived/jlens_mmpilot_v1/expanded_manifest.json``,
    which does not exist. The preparation cache lives under the same derived
    root on purpose — it is derived data — so the check is on the specific
    wrong path, not on the directory name.
    """
    source = _code_source(notebook)
    assert "jlens_mmpilot_v1" not in source
    assert "cstf_spokencoco_derived/jlens_mmpilot_v1" not in source
    for line in source.splitlines():
        if "expanded_manifest.json" in line and "cstf_spokencoco_derived" in line:
            raise AssertionError(f"manifest path guessed from the cache root: {line}")


def test_the_preparation_cache_is_deterministic_and_not_a_run(notebook):
    source = _code_source(notebook)
    assert 'PREP_CACHE_ROOT = "/content/drive/MyDrive/datasets/cstf_spokencoco_derived"' in source
    assert "preparation_cache_dir(PREP_CACHE_ROOT, PREPARATION_FINGERPRINT)" in source
    # The cache must not be keyed by a timestamped run directory: a preparation
    # that needed a run name could not be reused across sessions.
    assert "MMPILOT_RUN_DIR" not in source.split("# 8a.")[1].split("# 9.")[0]


def test_the_universe_is_recovered_from_the_cache(notebook):
    assert "universe_from_concept_annotations" in _code_source(notebook)
    assert "category_ids" in _source(notebook)


def test_disjointness_is_proven_over_all_four_identity_families(notebook):
    source = _code_source(notebook)
    assert "audit_population_disjointness" in source
    assert "assert_one_unit_per_photograph" in source
    assert "run_exclusion_preparation" in source
    assert "resolve_excluded_media" in source
    text = _source(notebook).lower()
    for family in ("image id", "group id", "recording", "caption text"):
        assert family in text


def test_preprocessing_is_checkpointed_resumable_and_proven_complete(notebook):
    source = _code_source(notebook)
    for name in (
        "preparation_fingerprint",
        "preparation_cache_dir",
        "run_exclusion_preparation",
        "assert_complete",
        "save_prepared_selection",
        "load_prepared_selection",
        "finalize_preparation",
        "render_preprocessing_report",
        "ProgressReporter",
    ):
        assert name in source, name
    assert "PREP_BATCH_FILES = 25" in source
    assert "PREP_CHECKPOINT_SECONDS = 30.0" in source
    assert "PREP_PROGRESS_SECONDS = 30.0" in source
    # The uncheckpointed double traversal is gone for good.
    assert "run_tree_digest" not in source
    assert "COMPLETED_TREES_BEFORE" not in source
    assert "assert_completed_runs_unchanged" not in source


def test_the_notebook_warns_against_preprocessing_on_a_gpu(notebook):
    source = _code_source(notebook)
    assert "torch.cuda.is_available()" in source
    text = _source(notebook).lower()
    assert "a gpu makes none of it faster" in text or "gpu provides no benefit" in text
    # Gemma is not loaded until the preparation is complete and verified.
    assert "if MODEL_STAGE_ENABLED and prep.preparation_is_complete(PREP_DIR) is None:" in source


def test_the_frozen_concepts_are_set_directly_and_only_checked(notebook):
    source = _code_source(notebook)
    assert "SELECTED_NAMES = list(SELECTED_CONCEPTS_EXPECTED)" in source
    assert "FOCAL_CONCEPTS = list(FOCAL_CONCEPTS_EXPECTED)" in source
    assert "assert_frozen_concepts_feasible" in source
    # The old rule refused unless a re-ranked top six matched the frozen six.
    assert "the independent pool ranks" not in source
    text = _source(notebook).lower()
    assert "descriptive only" in text


def test_the_frozen_criterion_digest_is_checked_not_recomputed(notebook):
    source = _code_source(notebook)
    assert "FROZEN_CRITERION_DIGEST" in source
    assert "CONVERGENCE_CRITERION(" not in source
    assert "ConvergenceCriterion(" not in source


def test_no_lens_is_fitted_or_modified(notebook):
    source = _code_source(notebook)
    for forbidden in ("fit_gemma", "jlens.fitting", "lens.save(", "fit_lens"):
        assert forbidden not in source


def test_steering_is_never_renamed_as_a_coordinate_swap(notebook):
    text = _source(notebook).lower()
    assert "two-coordinate swap" in text
    assert "separate future study" in text or "separate study" in text
    assert "from jlens.mmpilot.coordinate_swap import" not in _code_source(notebook)


def test_the_stage_b_rule_is_stated_as_an_efficiency_gate(notebook):
    text = _source(notebook).lower()
    assert "efficiency gate" in text
    assert "not a filter" in text or "not a way to suppress" in text
    assert "gate_overridden" in _code_source(notebook)


def test_the_report_phrasing_rule_is_enforced(notebook):
    source = _code_source(notebook)
    assert "assert_report_phrasing" in source
    text = _source(notebook).lower()
    assert "before native direct-readout convergence" in text
    for phrase in ("pre-linguistic", "language-free", "before language exists"):
        start = 0
        while (index := text.find(phrase, start)) != -1:
            window = text[max(0, index - 400) : index + 400]
            assert "never" in window, f"{phrase!r} used as a claim near: {window}"
            start = index + len(phrase)


def test_environmental_audio_is_never_claimed(notebook):
    text = _source(notebook).lower()
    assert "environmental (non-speech) audio" in text
    assert "nothing here measures it and nothing here" in text


def test_completed_runs_are_named_as_protected_and_proven_unchanged(notebook):
    source = _code_source(notebook)
    for prefix in ("rgext_", "mmaudio_", "rgcalib_", "mml32_l32_followup"):
        assert f'"{prefix}"' in source
    assert "PROTECTED_RUN_PREFIXES" in source
    assert "assert_fresh_run_namespace" in source
    # The proof is now the inventory re-enumeration, and the stronger guarantee
    # is structural: every preparation write path refuses a protected prefix.
    assert "assert_sources_unchanged" in source
    assert "verify_sources_unchanged" in source
    assert source.count("protected_prefixes=PROTECTED_RUN_PREFIXES") >= 5


def test_the_media_loaders_retry_drive_io(notebook):
    source = _code_source(notebook)
    assert "drive_media_loaders" in source
    assert "RetryJournal" in source
    # The bare, non-retrying loaders the previous notebook used are gone.
    assert 'sf.read(path, dtype="float32")' not in source
    assert "Image.open(path)" not in source


def test_the_sample_size_is_printed_before_any_model_is_loaded(notebook):
    cells = [c for c in _code_cells(notebook)]
    plan_cell = next(
        index
        for index, cell in enumerate(cells)
        if "format_sample_plan" in "".join(cell["source"])
    )
    model_cell = next(
        index
        for index, cell in enumerate(cells)
        if "build_real_backend" in "".join(cell["source"])
    )
    assert plan_cell < model_cell


def test_the_selection_seed_differs_from_the_completed_runs(notebook):
    source = _code_source(notebook)
    assert 'SPLIT_SEED = "spokencoco-l32-resolution-v1"' in source
    assert "spokencoco-l32-followup-v1" not in source.replace(
        '# "spokencoco-l32-followup-v1"', ""
    ) or 'SPLIT_SEED = "spokencoco-l32-followup-v1"' not in source


# ------------------------------------------------------------ MOCK execution


def _run(tmp_path, *overrides, stop_after=None, scratch=None):
    environment = dict(os.environ)
    environment.pop("PYTHONPATH", None)
    environment["MMPILOT_REPO_DIR"] = str(REPO_ROOT)
    environment["MMPILOT_SCRATCH"] = str(scratch or (tmp_path / "s"))
    arguments = [str(RUNNER), str(NOTEBOOK_PATH), *overrides]
    if stop_after is not None:
        arguments += ["--stop-after", str(stop_after)]
    result = subprocess.run(
        [sys.executable, *arguments],
        capture_output=True,
        text=True,
        cwd=str(tmp_path),
        env=environment,
    )
    payload = json.loads(result.stdout.strip().splitlines()[-1])
    return payload


def _ok(payload):
    assert payload.get("ok"), payload
    return payload


@pytest.fixture(scope="module")
def mock_run(tmp_path_factory):
    return _ok(_run(tmp_path_factory.mktemp("r1")))


@pytest.fixture(scope="module")
def mock_run_stage_b(tmp_path_factory):
    return _ok(
        _run(
            tmp_path_factory.mktemp("r2"),
            "RUN_STAGE_B_CAUSAL_REPLICATION=True",
            "CONFIRM_STAGE_B_BUDGET=True",
        )
    )


def test_the_mock_notebook_runs_end_to_end(mock_run):
    assert mock_run["n_cells"] > 20
    assert mock_run["mock_proves_pipeline_only"] is True
    assert mock_run["summary_schema"] == (
        "jlens.mmpilot.l32_convergence_resolution_summary.v1"
    )
    assert Path(mock_run["run_dir"]).name.startswith("mml32res_")


def test_the_mock_run_is_deterministic(tmp_path_factory, mock_run):
    again = _ok(_run(tmp_path_factory.mktemp("r3")))
    for key in (
        "primary_verdict",
        "VERDICT.classification",
        "SELECTED_NAMES",
        "FOCAL_CONCEPTS",
        "POPULATION_DIGEST",
        "exclusion_digest",
        "SAMPLE_PLAN_RECORD.plan_digest",
    ):
        assert again[key] == mock_run[key], f"{key} differed between MOCK runs"


def test_the_population_is_proven_disjoint_in_every_family(mock_run):
    assert mock_run["DISJOINTNESS.disjoint"] is True
    assert mock_run["DISJOINTNESS.failed_families"] == []
    assert set(mock_run["DISJOINTNESS.n_overlaps"]) == {
        "image_ids", "group_ids", "audio_paths", "captions",
    }
    assert all(value == 0 for value in mock_run["DISJOINTNESS.n_overlaps"].values())


def test_the_exclusion_really_excluded_something(mock_run):
    # A disjointness proof over an empty exclusion set proves nothing.
    assert mock_run["POOL_RECORD.n_groups_excluded"] > 0
    assert mock_run["exclusion_counts"]["image_ids"] > 0
    assert mock_run["exclusion_counts"]["audio_paths"] > 0
    assert mock_run["exclusion_counts"]["captions"] > 0


def test_there_is_one_photograph_and_one_recording_per_unit(mock_run):
    assert mock_run["PSEUDOREPLICATION.passed"] is True
    assert (
        mock_run["PSEUDOREPLICATION.n_units"]
        == mock_run["PSEUDOREPLICATION.n_distinct_images"]
        == mock_run["PSEUDOREPLICATION.n_distinct_recordings"]
    )


def test_the_selection_survives_a_permuted_manifest(mock_run):
    assert mock_run["SELECTION_DETERMINISM.deterministic"] is True


def test_the_cache_is_loaded_without_building_the_join(mock_run):
    assert mock_run["CACHE_LOAD.build_expanded_manifest_called"] is False
    assert mock_run["CACHE_LOAD.compatible"] is True
    assert mock_run["CACHE_LOAD.n_groups"] > 0
    assert mock_run["CACHE_LOAD.n_categories_recovered"] > 0
    assert mock_run["CACHE_LOAD.category_ids_available"] is False


def test_the_prompt_never_lists_the_candidates(mock_run):
    question = mock_run["OPEN_QUESTION"]
    for concept in mock_run["SELECTED_NAMES"]:
        assert concept not in question.lower(), (
            f"the candidate {concept!r} appears in the model-visible question"
        )


def test_the_controls_all_ran_and_all_passed(mock_run):
    assert mock_run["CONTROLS_RECORD.passed"] is True
    assert mock_run["CONTROLS_RECORD.missing_or_empty"] == []
    assert mock_run["CONTROLS_RECORD.failing"] == []


def test_the_mock_head_agreement_is_recorded_as_not_run_never_as_passed(mock_run):
    assert mock_run["HEAD_AGREEMENT.comparison_ran"] is False


def test_the_primary_verdict_is_one_of_the_four(mock_run):
    from jlens.mmpilot.l32_resolution import RESOLUTION_VERDICTS

    assert mock_run["primary_verdict"] in RESOLUTION_VERDICTS


def test_the_mock_world_converges_and_the_claim_is_ruled_out(mock_run):
    # The MOCK model's lm_head rows ARE the concept vectors and its final norm
    # is the identity, so its native readout is analytically clean and the layer
    # reads as CONVERGED. That is the correct MOCK outcome, and it is the branch
    # that must rule the pre-convergence claim out rather than support it.
    assert mock_run["primary_verdict"] == "L32_INDEPENDENT_CONVERGED"
    assert mock_run["SYNTHESIS.combined_pre_convergence_claim"] == (
        "RULED_OUT_AT_LAYER_32"
    )


def test_stage_b_does_not_run_when_the_gate_is_closed(mock_run):
    assert mock_run["STAGE_B.gate_met"] is False
    assert mock_run["STAGE_B.runs"] is False
    assert mock_run["STAGE_B.gate_overridden"] is False


def test_an_overridden_stage_b_runs_and_is_stamped_as_overridden(mock_run_stage_b):
    assert mock_run_stage_b["STAGE_B.runs"] is True
    assert mock_run_stage_b["STAGE_B.gate_met"] is False
    assert mock_run_stage_b["STAGE_B.gate_overridden"] is True
    assert "stage_b_causal_report.json" in mock_run_stage_b["artifact_names"]


def test_an_overridden_stage_b_does_not_complete_the_combined_claim(mock_run_stage_b):
    assert mock_run_stage_b["SYNTHESIS.combined_pre_convergence_claim"] != "SUPPORTED"
    assert mock_run_stage_b["SYNTHESIS.additional_causal_replication_required"]


def test_the_concepts_are_never_replaced(mock_run):
    assert mock_run["concepts_replaced_after_results"] is False


def test_the_phrasing_check_passes_on_the_generated_report(mock_run):
    assert mock_run["PHRASING.passed"] is True


def test_the_completed_runs_were_not_written_to(mock_run):
    assert mock_run["IMMUTABILITY.unchanged"] is True


def test_every_required_artifact_is_written(mock_run):
    for name in (
        "l32_convergence_resolution_summary.json",
        "l32_convergence_resolution_report.md",
        "population_manifest.json",
        "disjointness_audit.json",
        "convergence_tables.json",
        "convergence_controls.json",
        "run_state.json",
    ):
        assert name in mock_run["artifact_names"]


# --------------------------------------------------- interruption and resume


def test_an_interrupted_run_resumes_and_reuses_its_units(tmp_path_factory):
    """A half-finished run directory is picked up, not restarted.

    The first pass is cut off after the convergence-scoring cell, which is the
    only cell that writes readout units; the second pass runs the whole
    notebook against the same run directory and must report the units as
    *reused* rather than recomputed.
    """
    workspace = tmp_path_factory.mktemp("resume")
    scratch = workspace / "s"
    run_dir = workspace / "mml32res_mock_resume_test"
    environment_run_dir = str(run_dir)

    def _go(stop_after=None):
        environment = dict(os.environ)
        environment.pop("PYTHONPATH", None)
        environment["MMPILOT_REPO_DIR"] = str(REPO_ROOT)
        environment["MMPILOT_SCRATCH"] = str(scratch)
        environment["MMPILOT_RUN_DIR"] = environment_run_dir
        arguments = [str(RUNNER), str(NOTEBOOK_PATH)]
        if stop_after is not None:
            arguments += ["--stop-after", str(stop_after)]
        result = subprocess.run(
            [sys.executable, *arguments],
            capture_output=True,
            text=True,
            cwd=str(workspace),
            env=environment,
        )
        return json.loads(result.stdout.strip().splitlines()[-1])

    # 13b is the convergence-scoring cell and the only one that writes readout
    # units. Located by content rather than by index, because inserting a cell
    # above it used to silently turn this test into "run the whole notebook".
    payload = json.loads(NOTEBOOK_PATH.read_text(encoding="utf-8"))
    cells = [c for c in payload["cells"] if c["cell_type"] == "code"]
    stop = 1 + next(
        index
        for index, cell in enumerate(cells)
        if "run_single_layer_convergence(" in "".join(cell["source"])
    )
    interrupted = _go(stop_after=stop)
    assert interrupted.get("ok"), interrupted
    assert (run_dir / "convergence" / "readout_units").is_dir()
    n_units = len(list((run_dir / "convergence" / "readout_units").glob("*.json")))
    assert n_units > 0

    resumed = _ok(_go())
    assert resumed["RESUME.run_state"] == "resuming"
    assert resumed["RESUME.units_reused"] == n_units
    assert resumed["RESUME.units_computed"] == 0


def test_cpu_preprocessing_then_a_fresh_gpu_stage_reuses_the_preparation(
    tmp_path_factory,
):
    """The two-session workflow, in two genuinely separate processes.

    Session 1 is the CPU run: ``PREPROCESSING_ONLY`` closes every model gate,
    no run directory is created and nothing is scored. Session 2 is the
    Stage-A run against the same scratch: it must read **zero** source files,
    reconstruct the same population from Drive alone, and reach a verdict.
    """
    workspace = tmp_path_factory.mktemp("cpu_then_gpu")
    scratch = workspace / "s"

    cpu = _ok(_run(workspace, "PREPROCESSING_ONLY=True", scratch=scratch))
    assert cpu["MODEL_STAGE_ENABLED"] is False
    assert cpu["STAGE_A_ENABLED"] is False
    assert cpu["STAGE_B_REQUESTED"] is False
    assert cpu["RUN_STATE"] == "not_opened"
    assert cpu["artifact_names"] == []
    assert "primary_verdict" not in cpu
    assert cpu["PREP.files_computed_this_session"] > 0

    gpu = _ok(_run(workspace, scratch=scratch))
    assert gpu["PREP.files_computed_this_session"] == 0, (
        "a compatible completed preparation must perform zero source reads"
    )
    assert gpu["PREP.files_reused_from_drive"] == cpu["PREP.files_computed_this_session"]
    assert gpu["POPULATION_DIGEST"] == cpu["POPULATION_DIGEST"]
    assert gpu["exclusion_digest"] == cpu["exclusion_digest"]
    assert gpu["SELECTED_NAMES"] == cpu["SELECTED_NAMES"]
    assert gpu["primary_verdict"] in {
        "L32_INDEPENDENT_CONVERGED",
        "L32_INDEPENDENT_NOT_CONVERGED",
        "L32_INDEPENDENT_AMBIGUOUS",
    }


def test_preprocessing_only_writes_every_declared_preparation_artifact(
    tmp_path_factory,
):
    workspace = tmp_path_factory.mktemp("prep_artifacts")
    scratch = workspace / "s"
    payload = _ok(_run(workspace, "PREPROCESSING_ONLY=True", scratch=scratch))
    cache = Path(payload["PREP_DIR"])
    for name in (
        "preparation_fingerprint.json",
        "source_plan.json",
        "exclusion_set.json",
        "exclusion_set_checksum.json",
        "completeness_proof.json",
        "media_resolution.json",
        "independent_pool.json",
        "prepared_selection.json",
        "preparation_complete.json",
        "preprocessing_report.md",
    ):
        assert (cache / name).is_file(), name
    assert (cache / "harvest_minimal" / "harvest_state.json").is_file()
    assert (cache / "harvest_minimal" / "source_inventory.json").is_file()
    assert list((cache / "harvest_minimal" / "shards").glob("*.json.gz"))
    report = (cache / "preprocessing_report.md").read_text(encoding="utf-8")
    assert "no model output" in report
    assert "at most the single in-flight unit" in report


def test_a_changed_scientific_configuration_refuses_the_resume(tmp_path_factory):
    """Reusing a run directory under a different population is a refusal."""
    from jlens.mmpilot.convergence import ConvergenceFingerprint, ConvergenceStore
    from jlens.mmpilot.store import IncompatibleStateError

    root = tmp_path_factory.mktemp("fp") / "conv"
    common = dict(
        protocol="mmpilot.output_convergence_audit.v1",
        completed_run_fingerprint_digest="sha256:a",
        completed_run_dir=str(root),
        model_repo_id="mock/gemma-like",
        model_revision="mock",
        processor_revision="mock",
        layers=(1,),
        candidate_digest="sha256:candidates",
        readout_mode="single_token_complete",
        head_checksum="sha256:head",
        criterion_digest="sha256:criterion",
        code_version="mmpilot.l32_convergence_resolution.v1",
    )
    ConvergenceStore(
        root, ConvergenceFingerprint(**common, extra={"population_digest": "A"})
    ).open()
    with pytest.raises(IncompatibleStateError):
        ConvergenceStore(
            root, ConvergenceFingerprint(**common, extra={"population_digest": "B"})
        ).open()
