# Gemma 4 adaptation — new in this fork (github.com/anthropics/jacobian-lens is upstream).
# SPDX-License-Identifier: Apache-2.0
"""Structure and full MOCK execution of the open-prompt notebook.

The execution test runs every code cell in one namespace with the committed
switch left alone, so it checks two things at once: that the notebook works end
to end on CPU, and that opening it starts nothing. A second run flips the switch
and asserts that the notebook *refuses* — the real open-prompt study does not
exist, and the notebook must not improvise one.

The notebook is generated by ``scripts/_build_open_prompt_notebook.py``; the
structural tests here are what keep the generated file honest.
"""

import ast
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
NOTEBOOK_PATH = REPO_ROOT / "notebooks" / "open_prompt_protocol_mock_colab.ipynb"
BUILDER = REPO_ROOT / "scripts" / "_build_open_prompt_notebook.py"
RUNNER = Path(__file__).resolve().parent / "_open_prompt_notebook_runner.py"

REQUIRED_SECTIONS = [
    "colab bootstrap",
    "the switch, and why it refuses",
    "the legacy candidate-listed mode still functions",
    "the open prompt names no candidate",
    "every refusal, exercised",
    "the transcript is audited and never reaches the model",
    "the candidates are scored externally",
    "order must not move the fingerprint",
    "candidate-completion positions are never patched",
    "the mock effects",
    "summary",
]


@pytest.fixture(scope="module")
def notebook():
    return json.loads(NOTEBOOK_PATH.read_text(encoding="utf-8"))


def _code_cells(payload):
    return [cell for cell in payload["cells"] if cell["cell_type"] == "code"]


def _source(payload):
    return "\n".join("".join(cell["source"]) for cell in payload["cells"])


def _code_source(payload):
    return "\n".join("".join(cell["source"]) for cell in _code_cells(payload))


# ---------------------------------------------------------------- structure


def test_notebook_is_valid_and_output_free(notebook):
    assert notebook["nbformat"] == 4
    for index, cell in enumerate(_code_cells(notebook)):
        assert cell["outputs"] == [], f"code cell {index} has stored outputs"
        assert cell["execution_count"] is None, f"code cell {index} has an exec count"


def test_the_committed_notebook_matches_its_builder():
    result = subprocess.run(
        [sys.executable, str(BUILDER)], capture_output=True, text=True, cwd=REPO_ROOT
    )
    assert result.returncode == 0, result.stderr
    assert subprocess.run(
        ["git", "diff", "--quiet", "--", str(NOTEBOOK_PATH)], cwd=REPO_ROOT
    ).returncode == 0, (
        "the committed notebook differs from what its builder produces; run "
        "python scripts/_build_open_prompt_notebook.py and commit the result"
    )


def test_all_code_cells_parse_and_use_no_shell_magics(notebook):
    for index, cell in enumerate(_code_cells(notebook)):
        source = "".join(cell["source"])
        try:
            ast.parse(source)
        except SyntaxError as exc:  # pragma: no cover - failure path
            pytest.fail(f"code cell {index} does not parse: {exc}")
        for line in source.splitlines():
            assert not line.strip().startswith(("!", "%")), (
                f"code cell {index} uses a shell/line magic: {line!r}"
            )


def test_required_sections_are_present_in_order(notebook):
    text = _source(notebook).lower()
    position = 0
    for heading in REQUIRED_SECTIONS:
        found = text.find(heading, position)
        assert found >= 0, f"missing section {heading!r}"
        position = found


def test_the_notebook_never_loads_gemma_or_real_media(notebook):
    source = _code_source(notebook)
    for forbidden in (
        "AutoProcessor",
        "AutoModel",
        "Gemma4ForConditionalGeneration",
        "from_pretrained",
        "google/gemma",
        "drive.mount",
        "GemmaPilotBackend",
        "huggingface_hub",
        "soundfile",
        "from PIL",
        "PIL.Image",
    ):
        assert forbidden not in source, f"the MOCK notebook references {forbidden!r}"


def test_the_notebook_does_not_touch_a_completed_run(notebook):
    source = _source(notebook)
    for forbidden in (
        "rgext_real",
        "MyDrive",
        "/content/drive",
        "runs/pilot_",
        "mmaudio_",
        "jlens.calibration",
    ):
        assert forbidden not in source, f"the MOCK notebook references {forbidden!r}"


def test_the_only_switch_is_committed_false_and_refuses(notebook):
    source = _code_source(notebook)
    assert "RUN_REAL_OPEN_PROMPT_STUDY = False" in source
    assert "RUN_REAL_OPEN_PROMPT_STUDY = True" not in source
    assert "raise NotImplementedError" in source
    # Both blocking reasons have to be stated, not just the layer band.
    assert "CONTIGUOUS band" in source
    assert "untouched confirmation set" in source
    assert "unmeasured behavioural question" in source


def test_the_notebook_states_the_claim_boundaries(notebook):
    text = _source(notebook)
    assert "candidate-conditioned" in text
    assert "MOCK SUCCESS IS NOT SCIENTIFIC EVIDENCE" in text
    assert "stipulated, not measured" in text
    assert "spoken captions" in text
    assert "Behavioral outputs stay **text**" in text
    assert "separate claims" in text
    assert "hidden-intermediate reasoning merely because" in text


def test_the_notebook_never_renders_a_candidate_list_into_an_open_prompt(notebook):
    """The one string the open protocol exists to keep out of a prompt."""
    code = _code_source(notebook)
    assert "bird, cat, giraffe, microwave, toilet, zebra" not in code


# ---------------------------------------------------------------- execution


def _run(*overrides):
    environment = dict(os.environ)
    environment.pop("PYTHONPATH", None)
    environment["MMPILOT_REPO_DIR"] = str(REPO_ROOT)
    return subprocess.run(
        [sys.executable, str(RUNNER), str(NOTEBOOK_PATH), *overrides],
        cwd=REPO_ROOT.parent,
        env=environment,
        capture_output=True,
        text=True,
        timeout=900,
    )


@pytest.fixture(scope="module")
def executed():
    result = _run()
    assert result.returncode == 0, f"{result.stdout}\n{result.stderr}"
    return json.loads(result.stdout.strip().splitlines()[-1])


def test_the_notebook_runs_end_to_end_on_cpu(executed):
    assert executed["ok"] is True
    assert executed["run_real_open_prompt_study"] is False
    assert executed["mode"] == "mock"
    assert executed["status"] == "MOCK_PASSED"
    assert executed["loaded_gemma"] is False
    assert executed["torch_cuda_initialized"] is False


def test_the_legacy_prompt_is_reproduced_byte_for_byte(executed):
    legacy = executed["summary"]["legacy"]
    assert legacy["byte_for_byte_with_capability_module"] is True
    assert legacy["capability_protocol_string"] == "gemma-it-chat-balanced-options-v1"
    assert legacy["candidates_in_prompt"] is True
    assert legacy["maximum_claim"] == "candidate_conditioned_identification"


def test_the_open_prompts_name_no_candidate_in_any_modality(executed):
    section = executed["summary"]["open_identification"]
    assert section["question"] == (
        "What animal is present in the evidence? Answer with the animal name.\nAnswer:"
    )
    for modality, prompt in section["visible_prompt_by_modality"].items():
        for candidate in ("bird", "cat"):
            if modality == "text" and candidate == "bird":
                continue  # the caption legitimately says it; recorded below
            assert candidate not in prompt.lower(), (modality, candidate)
    assert section["candidates_are_external"] == {
        "text": True, "image": True, "spoken_audio": True
    }
    # The source is permitted and recorded in written evidence, and only there.
    assert section["source_in_visible_evidence"] == {
        "text": True, "image": False, "spoken_audio": False
    }
    # The target is nowhere: not in a prompt, not in the offline transcript.
    assert section["target_detected_anywhere"] == {
        "text": False, "image": False, "spoken_audio": False
    }


def test_every_refusal_fired(executed):
    assert set(executed["summary"]["refusals"]) == {
        "candidate_enumeration_in_the_open_question",
        "hidden_intermediate_source_in_transcript",
        "hidden_intermediate_source_in_visible_text",
        "hidden_intermediate_target_in_transcript",
        "property_answer_in_prompt",
        "semantic_filename_exposure",
        "target_in_audio_transcript",
        "target_in_visible_evidence",
        "unauditable_missing_transcript",
    }
    assert "source_in_visible_evidence" in executed["summary"]["protocol_separation"]


def test_the_transcript_never_crossed_into_the_backend(executed):
    assert executed["summary"]["transcript_reached_backend"] is False


def test_candidates_are_scored_externally_and_completely(executed):
    scoring = executed["summary"]["external_scoring"]
    assert scoring["all_multi_token"] is True
    assert scoring["order_invariance_max_abs_delta"] < 1e-9
    assert scoring["prompt_order_invariant"] is True


def test_order_leaves_the_fingerprint_alone_and_the_set_does_not(executed):
    assert executed["summary"]["fingerprint_sensitivity"] == {
        "order_changes_digest": False,
        "set_changes_digest": True,
        "set_changes_prompt_hash": False,
    }
    assert "not admissible for the primary" in executed["summary"][
        "primary_protocol_refusal"
    ]


def test_candidate_completion_positions_were_not_patched(executed):
    assert executed["summary"]["candidate_tail_bit_identical"] is True


def test_the_mock_effects_are_labelled_synthetic_and_support_no_claim(executed):
    summary = executed["summary"]
    assert summary["mock_effects"] == {
        "identity_clean": "bird",
        "identity_swapped": "cat",
        "property_clean": "two",
        "property_swapped": "four",
    }
    assert "synthetic plumbing only" in summary["mock_effects_are"]
    assert summary["ran_real_experiment"] is False
    assert all(admissible is False for admissible in summary["mock_claims_admissible"].values())


def test_the_notebook_is_deterministic():
    first, second = _run(), _run()
    assert first.returncode == 0 and second.returncode == 0
    a = json.loads(first.stdout.strip().splitlines()[-1])["summary"]
    b = json.loads(second.stdout.strip().splitlines()[-1])["summary"]
    assert a == b


def test_flipping_the_switch_refuses_instead_of_running_anything():
    result = _run("RUN_REAL_OPEN_PROMPT_STUDY=True")
    assert result.returncode == 1
    payload = json.loads(result.stdout.strip().splitlines()[-1])
    assert payload["ok"] is False
    assert "NotImplementedError" in payload["error"]
    assert "does not exist yet" in payload["error"]


# ------------------------------------------------------------ the schematic

SCHEMATIC_SVG = REPO_ROOT / "docs" / "assets" / "intervention_methods.svg"
SCHEMATIC_PNG = REPO_ROOT / "docs" / "assets" / "intervention_methods.png"


def test_the_schematic_draws_how_the_model_is_asked():
    svg = SCHEMATIC_SVG.read_text(encoding="utf-8")
    assert SCHEMATIC_PNG.read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"

    # The completed side: the prompt it actually used, and the claim it carries.
    for statement in (
        "COMPLETED — candidate-listed identification",
        "mmpilot.candidate_listed_identification.v1",
        "bird, cat, giraffe, microwave, toilet, zebra?",
        "every candidate concept is inside the model's own input",
        "not disclose which candidate is correct",
        "Supports: candidate-conditioned cross-modal causal steering.",
        "Does not establish spontaneous, unprompted concept emergence",
        "may prime their J-space representations",
    ):
        assert statement in svg, statement

    # The planned side: the open prompts, and the boundary the scorer sits on.
    for statement in (
        "PLANNED — open prompt, candidates external to the model",
        "mmpilot.open_identification.v1 / open_downstream_property.v1",
        "What animal is present in the evidence?",
        "How many legs does the animal typically have?",
        "no candidate list anywhere in the model-visible prompt",
        "candidates go only to the external teacher-forced scorer",
        "the swap target appears in no visible prompt and no transcript",
        "coordinate exchange (method B)",
        "separate conditions with separate claims",
    ):
        assert statement in svg, statement


def test_the_schematic_does_not_imply_the_open_experiments_have_succeeded():
    svg = SCHEMATIC_SVG.read_text(encoding="utf-8")
    assert "Not yet run. No result exists under any open protocol." in svg
    assert "No result under method B, and no result under any open protocol, exists yet." in svg
    assert "A hidden-intermediate test is a later, stronger stage" in svg
    assert "It is not designed yet." in svg
